### ISSUE TITLE
Do fizzbuzz with if, for statements

### ISSUE THREAD

**Issue by ulgoon** [kingwangzzang1234/team-fizzbuzz#1]
## Tasks

- [x] While i goes up 1 to 16
- [x] Print 'fizz' if i is times of 3
- [x] Print 'buzz' if i is times of 5
- [x] Print 'fizzbuzz' if i is times of 15
- [x] else, print i itself.
